version: '3.4'

services:
  accubatch:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  accumarkers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  accuorders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat


