version: '3.4'

services:
  accubatch:
    image: ${DOCKER_REGISTRY}accubatch
    build:
      context: .
      dockerfile: Services\AccuBatch\Dockerfile

  accumarkers:
    image: ${DOCKER_REGISTRY}accumarkers
    build:
      context: .
      dockerfile: Services\AccuMarkers\Dockerfile


  accuorders:
    image: ${DOCKER_REGISTRY}accuorders
    build:
      context: .
      dockerfile: Services\AccuOrders\Dockerfile

